#ifndef PHONONXINEEXPORT_H
#define PHONONXINEEXPORT_H

#include <kdemacros.h>

#ifdef Q_OS_WIN
# ifdef MAKE_PHONONXINEENGINE_LIB
#  define PHONON_XINE_ENGINE_EXPORT KDE_EXPORT
# else
#  define PHONON_XINE_ENGINE_EXPORT KDE_IMPORT
# endif
#else
# define PHONON_XINE_ENGINE_EXPORT KDE_EXPORT
#endif

#endif // PHONONXINEEXPORT_H
